Repository charmed-hpc/slurm-charms, pull requests merged in 2024-08, with the labels that each got.

#12 test: add additional integration checks
  repository.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
Labels: enhancement

#13 docs: update contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#20 chore(slurmd): SlurmdLogFile name correction
  charms/slurmctld/src/constants.py
Labels: bug
